### ISSUE TITLE
Simplify Dependencies Using Packages

### ISSUE THREAD

**Issue by bigtimebuddy** [PixiColorEffects/pixi-color-effects#3]
Another suggestion is to use **@pixi/core** instead of **pixi.js** for filter dependencies. This will support both pixi.js, pixi.js-legacy and custom bundles.

```js
// Before
import { Filter } from 'pixi.js';

// After
import { Filter } from '@pixi/core';
```

This is how https://github.com/pixijs/filters does it.

**Comment by carl-jin** [comment]
Thanks for u suggestion, I tried replace with "pixi/core" today, but some of filters based on the pixijs's build-in filter,  Can't simply deprecate pixi.js .

**Comment by bigtimebuddy** [comment]
Added a PR to address this more thoroughly @carl-jin
